export const PLANES = [
  {
    nombre: 'Gratis',
    precio_mensual: 0,
    precio_anual: 0,
    descripcion: 'Para conocer Fresco sin compromisos.',
    productos: 10,
    usuarios: 1,
    caracteristicas: [
      'Punto de venta básico',
      'Hasta 10 productos activos',
      '1 usuario',
      'Control de stock',
    ],
    bloqueadas: ['Reportes', 'Cierre de Caja', 'Alertas de stock', 'Movimientos de inventario'],
    cta: 'Comenzar gratis',
    ctaLink: '/registro',
    destacado: false,
  },
  {
    nombre: 'Básico',
    precio_mensual: 12000,
    precio_anual: 132480,
    descripcion: 'Ideal para almacenes y minimarkets pequeños.',
    productos: 800,
    usuarios: 4,
    caracteristicas: [
      'Todo lo del plan Gratis',
      'Hasta 800 productos',
      '4 usuarios',
      'Reportes del negocio',
      'Cierre de Caja (turno Z)',
      'Alertas de stock bajo',
    ],
    bloqueadas: ['Movimientos de inventario'],
    cta: 'Empezar ahora',
    ctaLink: '/registro',
    destacado: false,
  },
  {
    nombre: 'Pro',
    precio_mensual: 15000,
    precio_anual: 165600,
    descripcion: 'Para negocios en crecimiento con más equipo.',
    productos: 1200,
    usuarios: 6,
    caracteristicas: [
      'Todo lo del plan Básico',
      'Hasta 1.200 productos',
      '6 usuarios',
      'Catálogo maestro global',
      'Movimientos de inventario',
      'Roles avanzados (ADMIN, SUPERVISOR, CAJERO, BODEGA)',
    ],
    bloqueadas: [],
    cta: 'Empezar ahora',
    ctaLink: '/registro',
    destacado: true,
  },
  {
    nombre: 'Empresa',
    precio_mensual: 23000,
    precio_anual: 253920,
    descripcion: 'Para equipos grandes y operaciones multi-área.',
    productos: 2000,
    usuarios: 10,
    caracteristicas: [
      'Todo lo del plan Pro',
      'Hasta 2.000 productos',
      '10 usuarios',
      'Roles avanzados (ADMIN, SUPERVISOR, CAJERO, BODEGA)',
    ],
    bloqueadas: [],
    cta: 'Contactar ventas',
    ctaLink: '/registro',
    destacado: false,
  },
];