export const PLANES = [
  {
    nombre: 'Gratis',
    precio_mensual: 0,
    precio_anual: 0,
    descripcion: 'Para conocer Fresco sin compromisos.',
    productos: 10,
    usuarios: 1,
    caracteristicas: [
      'Punto de venta básico',
      'Hasta 10 productos activos',
      '1 usuario',
      'Control de stock',
    ],
    bloqueadas: ['Reportes', 'Cierre de Caja', 'Alertas de stock', 'Movimientos de inventario','Movimientos de caja'],
    cta: 'Comenzar gratis',
    ctaLink: '/registro',
    destacado: false,
  },
  {
    nombre: 'Básico',
    precio_mensual: 17990,
    precio_anual: 211562,
    descripcion: 'Ideal para almacenes y minimarkets pequeños.',
    productos: 800,
    usuarios: 3,
    caracteristicas: [
      'Todo lo del plan Gratis',
      'Hasta 800 productos',
      '3 usuarios',
      'Reportes del negocio',
      'Cierre de Caja (turno Z)',
      'Alertas de stock bajo',
      'Movimientos de inventario',
      'Roles',
    ],
    bloqueadas: [],
    cta: 'Empezar ahora',
    ctaLink: '/registro',
    destacado: false,
  },
  {
    nombre: 'Pro',
    precio_mensual: 23990,
    precio_anual: 282122,
    descripcion: 'Para negocios en crecimiento con más equipo.',
    productos: 1500,
    usuarios: 6,
    caracteristicas: [
      'Todo lo del plan Básico',
      'Hasta 1.500 productos',
      '6 usuarios',
      'Catálogo maestro global',
    ],
    bloqueadas: [],
    cta: 'Empezar ahora',
    ctaLink: '/registro',
    destacado: true,
  },
  {
    nombre: 'Empresa',
    precio_mensual: null,
    precio_anual: null,
    descripcion: 'Para cadenas y operaciones multi-local.',
    productos: null,
    usuarios: 10,
    caracteristicas: [
      'Todo lo del plan Pro',
      'Productos ilimitados',
      '10 usuarios',
      'Múltiples sucursales',
      'Precio personalizado',
    ],
    bloqueadas: [],
    cta: 'Contactar ventas',
    ctaLink: null,
    destacado: false,
  },
];