export const PLANES = [
  {
    nombre: 'Gratis',
    precio_mensual: 0,
    precio_anual: 0,
    descripcion: 'Para conocer Fresco sin compromisos.',
    productos: 10,
    usuarios: 1,
    caracteristicas: [
      'Punto de venta básico',
      'Hasta 10 productos activos',
      '1 usuario',
      'Control de stock',
    ],
    bloqueadas: ['Reportes', 'Cierre de Caja', 'Alertas de stock', 'Movimientos de inventario','Movimientos de caja'],
    cta: 'Comenzar gratis',
    ctaLink: '/registro',
    destacado: false,
  },
  {
    nombre: 'Básico',
    precio_mensual: 14990,
    precio_anual: 176282,
    descripcion: 'Ideal para almacenes y minimarkets pequeños.',
    productos: 800,
    usuarios: 4,
    caracteristicas: [
      'Todo lo del plan Gratis',
      'Hasta 800 productos',
      '4 usuarios',
      'Reportes del negocio',
      'Cierre de Caja (turno Z)',
      'Alertas de stock bajo',
      'Movimientos de inventario',
      'Roles',
    ],
    bloqueadas: [],
    cta: 'Empezar ahora',
    ctaLink: '/registro',
    destacado: false,
  },
  {
    nombre: 'Pro',
    precio_mensual: 17990,
    precio_anual: 211562,
    descripcion: 'Para negocios en crecimiento con más equipo.',
    productos: 1200,
    usuarios: 6,
    caracteristicas: [
      'Todo lo del plan Básico',
      'Hasta 1.200 productos',
      '6 usuarios',
      'Catálogo maestro global',
      
    ],
    bloqueadas: [],
    cta: 'Empezar ahora',
    ctaLink: '/registro',
    destacado: true,
  },
  {
    nombre: 'Empresa',
    precio_mensual: null,
    precio_anual: null,
    descripcion: 'Para equipos grandes y operaciones multi-área.',
    productos: 2000,
    usuarios: 0,
    caracteristicas: [
        'Todo lo del plan Pro',
      'Multiples sucursales',

    ],
    bloqueadas: [],
    cta: 'Contactar ventas',
    ctaLink: '/registro',
    destacado: false,
  },
];